#==========================================================================================
# FastAPI + Elasticsearch + BERT for embedding Document
# FastAPI 와 BERT 모델을 이용한 문서 임베딩
# - elasticsearch 7.17.13 사용
# - https://huggingface.co/bongsoo/kpf-sbert-128d-v1 모델 사용
# 
# * 설치전 data/settings.yaml 파일을 만들고, embed 켄터이너 구동에 필요한 설정값 변경이 필요함.(해당 파일은 구동시 자동 복사됨)
#===========================================================================================

version: '1.0'

services:
  es:
    image: elasticsearch:7.17.13
    environment:
      - discovery.type=single-node
    ports: 
      - 9200:9200
      - 9300:9300
    networks:
      - es_network
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.17.13
    ports:
      - 5601:5601
    networks:
      - es_network

  embed:
    image: bong9431/embed:2.0
    ports:
       - 9000:9000
       - 8888:8888
    networks:
       - es_network
    volumes:
       - /embed_log:/embed/FastAPI/log

volumes:
  es_data:

networks:
  es_network:
   
