version: '3'
services:
  mariadb:
    image: mariadb:11.1.2
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: password
    networks:
      - network01
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redmine:
    image: redmine:5.0.6
    container_name: redmine
    depends_on: 
      - mariadb
    environment:
      REDMINE_DB_MYSQL: mariadb
      REDMINE_DB_PASSWORD: password
    networks:
      - network01
    ports:
      - "3000:3000"
    volumes:
      - redmine_data:/usr/src/redmine/files

networks:
  network01:

volumes:
  mariadb_data:
  redmine_data:

