#==========================================================================================
# FastAPI + Elasticsearch + BERT for embedding Document
# FastAPI 와 BERT 모델을 이용한 문서 임베딩
# - elasticsearch 7.17.13 에 nori_tokenizer 설치한 bong9431/elasticsearch:7.17.13.1 사용 함.
# - https://huggingface.co/bongsoo/kpf-sbert-128d-v1 모델 사용
# 
# * embed 컨테이너 구동전 data 폴더를 compose.yml 파일 실행 경로에 넣고, 
#   구동에 필요한 settings.yaml 에 es ip등을 수정해야함.
#===========================================================================================

version: '1.0'

services:
  elasticsearch:
    image: bong9431/elasticsearch:7.17.13.1
    restart: always
    environment:
      - discovery.type=single-node
    ports: 
      - 9200:9200
      - 9300:9300
    networks:
      - es_network
    volumes:
      - esdata:/usr/share/elasticsearch/data
    
  kibana:
    image: kibana:7.17.13
    restart: always
    depends_on:
        - elasticsearch
    ports:
      - 5601:5601
    networks:
      - es_network

  embed:
      image: bong9431/embed:2.0
      restart: always
      depends_on:
        - elasticsearch
      ports:
        - 9000:9000
        - 8888:8888
      networks:
        - es_network
      volumes:
        - ./embed_log:/embed/FastAPI/log
        - ./data:/embed/FastAPI/data

volumes:
  esdata:

networks:
  es_network:
   
