# elasticsearch 7.17.x

version: '1.0'

services:
  elasticsearch:
    image: bong9431/elasticsearch:7.17.13.1
    restart: always
    environment:
      - discovery.type=single-node
    ports: 
      - 9200:9200
      - 9300:9300
    networks:
      - es_network
    volumes:
      - esdata:/usr/share/elasticsearch/data
    
  kibana:
    image: kibana:7.17.13
    restart: always
    depends_on:
        - elasticsearch
    ports:
      - 5601:5601
    networks:
      - es_network

  embed:
      image: bong9431/embed:3.0
      restart: always
      depends_on:
        - elasticsearch
      ports:
        - 9000:9000
        - 8888:8888
      networks:
        - es_network
      volumes:
        - ./embed_log:/embed/FastAPI/log
        - ./data:/embed/FastAPI/data

volumes:
  esdata:

networks:
  es_network:
   
